
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
something = { path = "../game", default-features = false }

[features]
default = ["something/default"]
dylib-engine = ["something/dylib-engine"]
